# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920b389265359fe06d7b3fa541573fac3e2c762dbd06511da5b148db7cd35e2706541e7d60da28e5c05b3916b2771c0f5ec4a0f68592190dc32c727931d0b6eb

test:
  secret_key_base: 0f116f8bbf6678c85ed60336eb1ef3c748714f28c9aa47625a4f5ec48a59b5ac192e289a87ab0fcec221bac9a1ce3f64f92348e9e13afce73f9d0b3c44a74bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
